version: '3.8'

services:
  mysql:
    image: mysql:8.1.0
    container_name: app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5ang15122003
      MYSQL_DATABASE: appfood
      MYSQL_USER: appuser
      MYSQL_PASSWORD: test123
    ports:
      - "3333:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: appfood-backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=test123  
      - MYSQL_DB=appfood
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
